### ISSUE TITLE
No module named 'tensorflow_core.estimator' error

### ISSUE THREAD

**Issue by swag94** [aamini/introtodeeplearning#40]
Gettting No module named 'tensorflow_core.estimator' error while running util.play_generated_song(text), though i have installed tensorflow

**Comment by eak65** [comment]
Most of the lab doesnt work

**Comment by aamini** [comment]
This sounds like you've installed an incorrect version of Tensorflow. 

What version of Tensorflow are you running? This lab was developed for use in Google colab and is supported with TensorFlow 1.13.0

**Comment by iammerrick** [comment]
(Cross-posted from another issue with the same root cause.)

👋 Hello, future deep learning lab adventurer. Ideally, these notebooks are always up to date or maybe they could include a setup.py file 😉? 

Until then Google Collab allows you to "Copy to drive" and modify the Notebook. In which case you can add a new code block to install a specific version `!pip install tensorflow==1.14`.

![image](https://user-images.githubusercontent.com/109635/67153370-30935b80-f2a5-11e9-8587-610f1dc73424.png)

**Comment by aamini** [comment]
@iammerrick We've fixed this in the new version of the course and included a new `mitdeeplearning` package with a seetup.py script for installing deps.
