### ISSUE TITLE
can't play song. 

### ISSUE THREAD

**Issue by SyedWaqar-ah** [aamini/introtodeeplearning#58]
the code 
mdl.lab1.play_song(    )
is not responsive on local host. No error nor long wait, it simply completes tasks and does nothing

**Comment by aamini** [comment]
Hi, Are you running the lab on Colab? Currently this is the platform we are supporting.

**Comment by SyedWaqar-ah** [comment]
No I downloaded the mitdeeplearning package and am currently running on my system I commented all the assertion commands to avoid prompts. 
It is currently training and so far everything seems good. But I'm not sure how will I listen to the generated output

**Comment by aamini** [comment]
Generating the song requires synthesizing the ABC format generated audio into wav files. Currently this is supported using the abc2wav script. You could take a look at this script to see what might be causing the issue but I recommend running in Colab since the code has already been tested to run on that platform successfully. Thanks!
