### ISSUE TITLE
Incorrect matrix operation in Lab 1

### ISSUE THREAD

**Issue by brilliant-ember** [aamini/introtodeeplearning#64]
What a Keras dense layer do is this: `output = activation(dot(input, kernel) + bias)`  -(1) Noting that the matrix operation between the kernel (weights) and the input is a dot product NOT matrix multiplication.

Lab 1, section 1.3 graph and the code todo comment incorrectly says to use tf.matmul() which is matrix multiplication, instead it we should use the dot product function, as is the case with the Dense layer doc link below (1)

![image](https://user-images.githubusercontent.com/23269759/80500068-b6bae980-893b-11ea-8972-8ae2e7b71795.png)

![image](https://user-images.githubusercontent.com/23269759/80500300-08637400-893c-11ea-9082-a35ee525622c.png)

(1) https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dense?version=stable

**Comment by aamini** [comment]
I believe this is not an error (the original code is correct). Matrix multiply is equivalent to many dot products. When considering a single batch we do a dot product, but in general with batches of features matrix multiply is the convention. If you look at how the official TensorFlow Dense layer is implemented, a matrix multiply op is used: https://github.com/tensorflow/tensorflow/blob/e5bf8de410005de06a7ff5393fafdf832ef1d4ad/tensorflow/python/keras/layers/core.py#L1142

Both will ultimately work, since dot products of two vectors is identical to the matrix multiply. https://www.quora.com/What-is-the-difference-between-dot-product-and-matrix-product/answer/David-Joyce-11?ch=10&share=af8822be&srid=T8lR
